#! /usr/bin/env bash
IP_ADDRESS=192.168.0.130
if [ "$1" != "" ] ; then
    IP_ADDRESS=$1
fi

arm-none-eabi-gdb -ex "set target-charset ASCII" -ex "set print pretty on" -ex "set remotelogfile mri.log" -ex "target remote $IP_ADDRESS:23" LPC1768/*.elf
